eslintを追加する
shikky0331/shikky pull request #14
Opened 2021-06-22 23:50 UTC by shikky0331

2021-06-23 01:12 UTC, piro0919 requested changes
[must]

eslint の設定は何を参考にされたのか教えていただきたいです。 👍

2021-06-23 01:12 UTC, piro0919 commented on package.json
> +    "src/**/*.{ts,tsx}": "eslint --fix"
[imo]

`scripts` 側にも記述しましょうか。 🐱

2021-06-23 01:12 UTC, piro0919 commented on .eslintrc.json
> +}
[must]

インデントが 4 ですね。
2 で統一したいので、ご確認お願いします。 🙇

2021-06-23 01:12 UTC, piro0919 commented on .eslintrc.json
> +        "react/react-in-jsx-scope": "off"
[must]

追加で `off` にされている理由をお願いしますー。 👍

2021-06-23 01:16 UTC, piro0919 commented
@shikky0331 

あとブランチが `feature` から切られていないですね。

単なるミスですかね？

2021-06-23 23:24 UTC, shikky0331 commented
@piro0919 
> eslint の設定は何を参考にされたのか教えていただきたいです。 👍

基本的には`eslint --init`で作成しました！
スタイルガイドで`airbnb`を使用したのは特に深く考えてなかったです🙇‍♂️
https://qiita.com/uhooi/items/f22b53b6e39228fc4826#%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E4%BD%9C%E6%88%90

`"extends": "eslint:recommended"`は公式（https://eslint.org/docs/user-guide/getting-started）に記載されていたのでそのまま利用しました。

2021-06-23 23:28 UTC, shikky0331 commented on .eslintrc.json
> +        "react/react-in-jsx-scope": "off"
@piro0919 
> With the new transform, you can use JSX without importing React.

React version 17からJSXを使用する際に`import React from `react``が必要なくなったので、公式の設定をそのまま使用しました！
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#eslint

2021-06-23 23:28 UTC, shikky0331 commented
@piro0919 
> あとブランチが feature から切られていないですね。 👀

すみません。これはミスです🙇‍♂️
修正します！

2021-06-23 23:33 UTC, shikky0331 commented
@piro0919 
あ、リモートのブランチ名を変更するには、削除して新規作成するしかないのでプルリクもcloseされてしまうのですね。。
今回のケースはどうすればいいでしょうか？mm

2021-06-24 01:01 UTC, piro0919 commented on .eslintrc.json
> +        "react/react-in-jsx-scope": "off"
@shikky0331 

これ知らなかったです！
ありがとうございますー。 👍

2021-06-24 01:03 UTC, piro0919 commented
@shikky0331 

https://github.com/shikky0331/shikky/pull/14#issuecomment-867224695
> 今回のケースはどうすればいいでしょうか？mm

おまかせしますー。
本 PR のレビューが通ったらブランチを切り直して PR を上げ直して、この PR に紐づけてこちらを close するとかですかね？

面倒でしたらこのまま進めても良いですよ。

2021-06-24 05:00 UTC, shikky0331 commented
@piro0919 
https://github.com/shikky0331/shikky/pull/14#issuecomment-867255259
> 面倒でしたらこのまま進めても良いですよ。

今回はこのまま進めます🙇‍♂️

2021-06-24 05:03 UTC, shikky0331 commented
@piro0919 
https://kk-webhq.slack.com/archives/C024R9NTR8X/p1624497073003500
共有してくださった記事見ました！
style guideは設定が一番厳しそうな`airbnb`にしようと思います。

使用しててlint設定が厳しすぎて不便があれば、都度修正していこうかなと思います

2021-06-24 05:10 UTC, piro0919 commented on package.json
> +    "src/**/*.{ts,tsx}": "eslint --fix"
@piro0919 

18e5b45 において修正しました。 🙇

2021-06-24 05:24 UTC, shikky0331 commented on package.json
> +    "src/**/*.{ts,tsx}": "eslint --fix"
@piro0919 
こちらのhttps://github.com/shikky0331/shikky/pull/14/commits/18e5b45fbf4f435b2a826c58db5fa6352d72b61a で追記しました！

2021-06-24 05:24 UTC, shikky0331 commented on .eslintrc.json
> +}
@piro0919 
https://github.com/shikky0331/shikky/pull/14/commits/860c215e869f1df6f2858578c9b3cb5d5d65b8a4 インデント修正いたしました🙇‍♂️

2021-06-24 05:28 UTC, piro0919 commented on .eslintrc.json
> +}
@shikky0331 

まだ直っていないと思いますー。 🙇 
おそらく手動で直されていると思いますので、vscode 側の設定を変えて自動フォーマットがかかるようにしてみてください。 👍

2021-06-24 05:29 UTC, piro0919 requested changes
再度ご確認よろしくお願いします。 🙇 

rel https://github.com/shikky0331/shikky/pull/14#discussion_r657636446

2021-06-24 09:58 UTC, shikky0331 commented on .eslintrc.json
> +}
@piro0919 
確認不足でした。すみません🙇‍♂️
https://github.com/shikky0331/shikky/pull/14/commits/a451a15d917f1adbb44f55e0593cab7e02c51aaa こちらで変更しました。

2021-06-25 04:15 UTC, piro0919 approved these changes
LGTM 👍

2021-06-25 04:15 UTC, merged