react-router-domを追加してホームページを作成
shikky0331/shikky pull request #22
Opened 2021-06-29 23:41 UTC by shikky0331

2021-06-29 23:44 UTC, shikky0331 commented
@piro0919 
https://github.com/shikky0331/shikky/issues/9#issuecomment-864649572
> ページ設計が決まりましたら react-router-dom の導入から、各 container components を切るところまで進めてください。 👍

作業が完了したのですが、ここまでで大丈夫でしょうか？
お時間あるときにご確認をお願いします🙇‍♂️

2021-06-29 23:47 UTC, piro0919 requested changes

2021-06-29 23:47 UTC, piro0919 commented on src/pages/home/index.tsx
> +export default Home;
[must]

ルーティングに沿えていないですね。 🙅‍♂️ 
`pages` フォルダ以下に切るほうが良いですね。 👍

2021-06-29 23:47 UTC, piro0919 commented on src/App.tsx
>  function App() {
[must]

`App` コンポーネントを起点にするメリットもないと思うので、ちょっとフォルダ構成を変えたほうが良いかなーと思います。 👀

2021-06-29 23:48 UTC, piro0919 commented
@shikky0331 

個人的には `src` 直下に `containers` フォルダを切って、そこを起点にするほうがスムーズにいけるかなーと思いますがいかがでしょうか。

2021-06-29 23:55 UTC, shikky0331 commented
@piro0919 
> 個人的には src 直下に containers フォルダを切って、そこを起点にするほうがスムーズにいけるかなーと思いますがいかがでしょうか。

すみません。具体的なイメージができていないのですが、`containers`以下には`page`フォルダを置く感じでしょうか？

2021-06-29 23:57 UTC, piro0919 commented
@shikky0331 

https://github.com/shikky0331/shikky/pull/22#issuecomment-870993826

上記で認識に相違ないですー。
container components は `containers` フォルダ以下に、presentational components は `components` フォルダ以下に切っていくのが個人的には開発しやすかったですが、どうでしょうか？

2021-06-30 00:06 UTC, shikky0331 commented
@piro0919 
今回は https://github.com/shikky0331/shikky/pull/22#issuecomment-870994884 の構成でいこうと思います！

`containers`ディレクトリを挟まずに、`page`ディレクトリを置いてもいいのかなとも思ったのですが、`containers`を挟む理由は何かあるのでしょうか？

2021-06-30 00:10 UTC, piro0919 commented
@shikky0331 

デフォルトで static なケース（Next.js や Gatsby） の場合、ルーティングをハンドリングするコンポーネントが不要なので `containers` フォルダを切らなくても良いですし、切る必要もないと思います。（実際自分も切らないですね）
Create React App の場合ルーティング用のファイルが必要なため、`container` フォルダを切って、フォルダ直下にハンドリング用のコンポーネントを切ることが多いですね。

2021-06-30 00:10 UTC, shikky0331 commented
あ、ホームページと起点になるファイルが同じ階層になってしまうからですかね👀

2021-06-30 00:12 UTC, shikky0331 commented
@piro0919 
https://github.com/shikky0331/shikky/pull/22#issuecomment-871000859
理解できました！スッキリしました！ありがとうございます🙇‍♂️

2021-06-30 23:33 UTC, shikky0331 commented on src/pages/home/index.tsx
> +export default Home;
@piro0919 
`pages`フォルダ直下にHome Containerを移動し、
https://github.com/shikky0331/shikky/pull/22/commits/af5836ed8669337c6e93829725ec31bfe6c86997
フォルダ構成に合わせてContainerの名前を`Home`から`Pages`に変更しました。
https://github.com/shikky0331/shikky/pull/22/commits/d839e799eafcdffc0abddf766240e4dae9e6f9c8

2021-06-30 23:36 UTC, shikky0331 commented on src/App.tsx
>  function App() {
@piro0919 
`container`直下にルーティングファイルを移動し、
https://github.com/shikky0331/shikky/pull/22/commits/7577be01029d263511155f96d0b601e873cf212a
ファイル名を`App.tsx`から`index.tsx`に変更しました。
https://github.com/shikky0331/shikky/pull/22/commits/87ac8c2dbbb648bb99773fbabb20716f9260e392

2021-06-30 23:39 UTC, shikky0331 commented
@piro0919 
https://github.com/shikky0331/shikky/pull/22#issuecomment-870991560
`container`フォルダを作成し、フォルダ構成を変更しました！
お手隙の際にご確認をお願いします🙇‍♂️

2021-07-01 01:00 UTC, piro0919 reviewed
大体良いと思いますー。 👍

2021-07-01 01:00 UTC, piro0919 commented on src/containers/index.tsx
> +import Pages from 'containers/pages/index';
[imo]

import 文に `index` は書かなくても良かったような気がしますね。
linter 側の制約ですかね？

2021-07-01 01:00 UTC, piro0919 commented on src/index.tsx
> +import Containers from 'containers/index';
[imo]

import 文に `index` は書かなくても良かったような気がしますね。
linter 側の制約ですかね？

2021-07-01 11:56 UTC, shikky0331 commented on src/index.tsx
> +import Containers from 'containers/index';
@piro0919 
ファイル名を変更したときに、vscode側で自動にimportされているpathを変更したので、`index`がついてしまったようです。
こちらで修正しました🙇‍♂️
https://github.com/shikky0331/shikky/pull/22/commits/bb192fc0389abdb6533ece6e85ff35fc8c7f5f89

2021-07-01 11:56 UTC, shikky0331 commented on src/containers/index.tsx
> +import Pages from 'containers/pages/index';
@piro0919 
ファイル名を変更したときに、vscode側で自動にimportされているpathを変更したので、`index`がついてしまったようです。
こちらで修正しました🙇‍♂️

https://github.com/shikky0331/shikky/pull/22/commits/2fcd17eed4c725736b36f84f8e2fb0a65e827529

2021-07-03 07:15 UTC, piro0919 approved these changes
LGTM 👍

2021-07-03 07:15 UTC, merged