ホームページを追加する
shikky0331/shikky pull request #24
Opened 2021-07-06 00:10 UTC by shikky0331

2021-07-06 00:31 UTC, piro0919 requested changes
ちょっと html のフォーマッターの仕様が怪しいですが。 👀

2021-07-06 00:31 UTC, piro0919 commented on src/components/templates/Blog/style.module.scss
> +
[must]

この書き方は CSS Modules でやってはいけない書き方の 1 つですね。 🙅‍♂️ 
なぜこの書き方が良くないのか、修正を行う前に少し考えてみてください。 👍

2021-07-06 00:31 UTC, piro0919 commented on src/components/templates/Blog/index.tsx
> +import styles from 'components/templates/Blog/style.module.scss';
[must]

せっかく CSS のカプセル化を行っているので、相対パスで書いたほうがわかりやすいと思います。 👍

2021-07-06 00:31 UTC, piro0919 commented on src/components/templates/Blog/index.tsx
> +    <article>
[imo]

`article` は `heading` 要素とセットで使わないとダメだったような気がします。
あとから内部に `header` などを追加する認識であれば OK です。 👌

2021-07-07 00:35 UTC, shikky0331 commented on src/components/templates/Blog/style.module.scss
> +
@piro0919 
classではなくtagに直接cssを指定するとスコープがグローバルになってしまうので、CSS Modulesの利点が活かせないのですね🙇‍♂️
上記の認識で合ってるでしょうか？

下記で修正しました。
https://github.com/shikky0331/shikky/pull/24/commits/5e3a6c31fada6e7af62aedce99afebb78aec462f

2021-07-07 00:36 UTC, shikky0331 commented on src/components/templates/Blog/index.tsx
> +import styles from 'components/templates/Blog/style.module.scss';
確かにそうですね！
絶対パスで書くのが癖になっていましたmm

修正しました！
https://github.com/shikky0331/shikky/pull/24/commits/114be7487066a68193d4b3c4a38a95f85c413951

2021-07-07 00:40 UTC, shikky0331 commented on src/components/templates/Blog/index.tsx
> +    <article>
@piro0919 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article#usage_notes
調べてみたら、hタグと一緒に使うべきであると書いてありました📝

そもそも外側を`article`で囲む必要もないと思ったので、`main`の方にCSSを追加して修正しました。
https://github.com/shikky0331/shikky/pull/24/commits/9500e0a89c985575640f65cae3784860ca615e03

2021-07-07 00:48 UTC, piro0919 commented on src/components/templates/Blog/style.module.scss
> +
@shikky0331 

ばっちりです素晴らしい 👍 
追記すると、グローバルスコープになってしまうと想定外の当たり方をしてしまう可能性があるので、CSS Modules ではすべてクラス名で指定するようにしましょう。 👍

2021-07-07 00:53 UTC, piro0919 approved these changes
LGTM 👍

2021-07-07 00:53 UTC, merged