Footerを追加
shikky0331/shikky pull request #31
Opened 2021-07-09 23:51 UTC by shikky0331

close #26

﻿

2021-07-10 01:17 UTC, piro0919 commented
@shikky0331 

rel https://github.com/shikky0331/shikky/issues/26#issue-937428641
> フッターコンポーネントを作成する。

ちょっと issue の内容と認識がずれてますかね？
`organisms` フォルダ以下に `Footer` コンポーネントを切ってもらって良いと思いますが、どうでしょうか。 👀

2021-07-10 23:24 UTC, shikky0331 commented
@piro0919 
すみません！認識がずれてました！
一度`templates/Blog`に全て書くものかと勘違いしてました🙇‍♂️

`organisms/Footer`として書きます🐘

2021-07-10 23:44 UTC, shikky0331 commented
@piro0919 
`organisms/Footer`としてComponentを切り出しました
[`8f041f4` (#31)](https://github.com/shikky0331/shikky/pull/31/commits/8f041f44e199832749a58778ec147c101d146ace)

2021-07-12 01:25 UTC, piro0919 requested changes

2021-07-12 01:25 UTC, piro0919 commented on src/components/organisms/Footer/index.tsx
> +const Footer = () => (
[imo]

containers 側では VFC が使用されているみたいですは、Footer 側で型をつけない理由って何かありますか？

rel https://github.com/shikky0331/shikky/pull/31/files#diff-b41670b06f1be74002b15dbd3836059f6d8fb23714701bf02264826603e87da6L5

2021-07-12 01:25 UTC, piro0919 commented on src/components/organisms/Footer/style.module.scss
> +  padding-top: 5em;
[must]

`padding` を `Footer` 内に内包するのは Atomic Design の仕様に沿えていないですね。 🙅‍♂️ 
`templates` 側に移動させちゃいましょう。 👍

2021-07-14 23:23 UTC, shikky0331 commented on src/components/organisms/Footer/style.module.scss
> +  padding-top: 5em;
@piro0919 
こちらで対応しました🙇‍♂️
[`43c8b72` (#31)](https://github.com/shikky0331/shikky/pull/31/commits/43c8b72f1b8b70a6e919171c3ef9f2d778960980)

2021-07-14 23:24 UTC, shikky0331 commented on src/components/organisms/Footer/index.tsx
> +const Footer = () => (
@piro0919 
つけ忘れです。。
こちらで追加しました🙇‍♂️
[`313ff86` (#31)](https://github.com/shikky0331/shikky/pull/31/commits/313ff86db8ec9dcac5f55569fc9d74087b6c3225)

2021-07-15 01:07 UTC, piro0919 reviewed
コンフリクトの修正お願いしますー。 👍

2021-07-15 23:10 UTC, shikky0331 commented
@piro0919 
修正いたしました🙇‍♂️

2021-07-16 01:02 UTC, piro0919 approved these changes
LGTM 👍

2021-07-16 01:02 UTC, merged