記事一覧をAtomic Designに落とし込む
shikky0331/shikky pull request #39
Opened 2021-07-20 00:11 UTC by shikky0331

close #10

2021-07-20 02:32 UTC, piro0919 requested changes
[imo]

presentational components を切られる際は同時に story も切ってしまったほうが良いかなーと思いますが、どうでしょうか。
別 issue で対応される予定でしたら問題ないです。 👌

2021-07-20 02:32 UTC, piro0919 commented on src/components/organisms/ArticleList/index.tsx
> +  <>
[must]

リストという名前なので、HTML 的にもリストにしちゃったほうが良いかなーと思います。
あとからスタイルを追加したくなったときなどに、柔軟性が上がると思いますね。 👍

2021-07-20 02:32 UTC, piro0919 commented on src/components/molecules/Article/style.module.scss
> +  padding-top: 5em;
[must]

この padding は organisms ですね。 👀

2021-07-20 02:32 UTC, piro0919 commented on src/components/atoms/ArticleTitle/style.module.scss
> +  margin-block-end: 0.5em;
[imo]

これちょっと微妙ですね…本来論としては atoms に持たせて良い margin ではないと思います。
きちんと設定するならここには 0 を設定して、上位のコンポーネントで間隔を設定してあげるべきだと思います。 👍

2021-07-20 02:32 UTC, piro0919 commented on src/components/templates/Blog/index.tsx
> +interface BlogProps {
[nits]

確か最近は interface でなく type のほうが推奨されていた気がしますね。
個人的には統一されていればどちらでも良いですが。 👍

2021-07-20 02:32 UTC, piro0919 commented on src/components/templates/Blog/index.tsx
> +interface BlogProps {
[must]

コンポーネント唯一の公開情報なので使用の有無に関わらず props の型には export をつけましょう！
逆にコンポーネントファイルが export して良い型は props だけですね。

2021-07-20 02:32 UTC, piro0919 commented on src/components/organisms/ArticleList/index.tsx
> +      <Article url={url} title={title} date={date} introduction={introduction} />
[must]

key が設定されてないですね。 🙅‍♂️ 
別 issue を立てたので、先にこちらの対応をお願いしますー。 🙇 

rel https://github.com/shikky0331/shikky/issues/40

2021-07-20 02:32 UTC, piro0919 commented on src/components/molecules/Article/index.tsx
> +  <article className={styles.post}>
[nits]

post って名前はちょっと微妙かと…article とか wrapper とかですかね。

2021-07-20 23:18 UTC, shikky0331 commented on src/components/organisms/ArticleList/index.tsx
> +      <Article url={url} title={title} date={date} introduction={introduction} />
#41 でeslint-plugin-reactを追加しましたmm

[`e8de904` (#39)](https://github.com/shikky0331/shikky/pull/39/commits/e8de904aa8ebc6b233701e4d331e64c6ef23a832)
keyを追加しました！

2021-07-20 23:19 UTC, shikky0331 commented on src/components/organisms/ArticleList/index.tsx
> +  <>
確かに名前と構造に剥離がありますね、、

[`9e84d5c` (#39)](https://github.com/shikky0331/shikky/pull/39/commits/9e84d5c53a3a8c3d0b48ca1191f6b5311779b32e)
リスト構造に変更しました！

2021-07-20 23:21 UTC, shikky0331 commented on src/components/molecules/Article/index.tsx
> +  <article className={styles.post}>
しっかりと確認できてなかったです🙇‍♂️

[`d6b8d10` (#39)](https://github.com/shikky0331/shikky/pull/39/commits/d6b8d10609902b9e82fc0003b4b5cb495841120d)
wrapperに修正しました！

2021-07-20 23:22 UTC, shikky0331 commented on src/components/molecules/Article/style.module.scss
> +  padding-top: 5em;
[`d6b8d10` (#39)](https://github.com/shikky0331/shikky/pull/39/commits/d6b8d10609902b9e82fc0003b4b5cb495841120d)
ArticleListで定義しました🙇‍♂️

2021-07-20 23:25 UTC, shikky0331 commented on src/components/atoms/ArticleTitle/style.module.scss
> +  margin-block-end: 0.5em;
なるほどです！📝
どのComponentに`mergin`, `padding`を持たせるべきかの理解が曖昧なので、もう一度学び直したいと思います🙇‍♂️

[`d14d84b` (#39)](https://github.com/shikky0331/shikky/pull/39/commits/d14d84b2fa7227e50ab80de244ea393d97ae5393)
修正しましたmm

2021-07-20 23:27 UTC, shikky0331 commented on src/components/templates/Blog/index.tsx
> +interface BlogProps {
[`7d63ae8` (#39)](https://github.com/shikky0331/shikky/pull/39/commits/7d63ae8c7638bb9570ea0a0ee8258c867247c424)
こちらで`export`しました

2021-07-20 23:34 UTC, shikky0331 commented on src/components/templates/Blog/index.tsx
> +interface BlogProps {
> 確か最近は interface でなく type のほうが推奨されていた気がしますね。
> 個人的には統一されていればどちらでも良いですが。 👍

違いの理解が曖昧なので、調べたいと思います！

2021-07-20 23:36 UTC, shikky0331 commented on src/components/molecules/Article/style.module.scss
> +  padding-top: 5em;
[`afc1e8f` (#39)](https://github.com/shikky0331/shikky/pull/39/commits/afc1e8fcc540e1d38ec7a1d8c344dc4980552115)
CSSを`li`タグに付与してしまい、globalなstyleになってしまっていました🙇‍♂️
修正しました

2021-07-20 23:37 UTC, shikky0331 commented
@piro0919 
https://github.com/shikky0331/shikky/pull/39#pullrequestreview-710121621

StoryBookも同じプルリクで実装します！mm

2021-07-26 00:31 UTC, shikky0331 commented on src/components/templates/Blog/index.tsx
> +interface BlogProps {
`Declaration merging`などの細かい違いはありますが、どちらを使っても大差はなさそうでした。
仕事のプロジェクトが`interface`をメインに使用しているので、`type`でいきたいと思います！

[`b377954` (#39)](https://github.com/shikky0331/shikky/pull/39/commits/b3779548cd8db8123c84197987f8753349ea003f)

2021-07-26 00:32 UTC, shikky0331 commented on src/components/organisms/ArticleList/index.tsx
> +      <Article url={url} title={title} date={date} introduction={introduction} />
`key`を付与する場所が間違っていたので、修正いたしましたmm

[`39283c6` (#39)](https://github.com/shikky0331/shikky/pull/39/commits/39283c65934700b76e83a8c2389d04d6f6b5ca87)

2021-07-26 00:33 UTC, shikky0331 commented
@piro0919 
storybookを追加しました。お手隙の際に、ご確認をお願いします🙇‍♂️

2021-07-26 01:56 UTC, piro0919 requested changes

2021-07-26 01:56 UTC, piro0919 commented on .storybook/preview.js
> +import { MemoryRouter } from "react-router";
[must]

react-router-dom でいけると思います。 👀 
以下で対応できないですかね？

`import { MemoryRouter as Router } from 'react-router-dom';`

2021-07-26 09:54 UTC, shikky0331 commented on .storybook/preview.js
> +import { MemoryRouter } from "react-router";
react-router-dom で対応できました🙇‍♂️

[`c1b374a` (#39)](https://github.com/shikky0331/shikky/pull/39/commits/c1b374a071595441c86da702b3d7a7343a823be1)

2021-07-26 12:15 UTC, piro0919 approved these changes
LGTM 👍

2021-07-26 12:16 UTC, merged