commitlintを追加する
shikky0331/shikky pull request #4
Opened 2021-06-17 23:23 UTC by shikky0331

2021-06-17 23:33 UTC, piro0919 commented
@shikky0331 

PR を Issue に紐付ける場合、PR のコメントと Issue の番号を close コメントで紐付けるようにしてください。 👍 
https://docs.github.com/ja/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2021-06-17 23:33 UTC, piro0919 requested changes
[must]

husky が導入されていないように見えます。 👁️ 
再度 Issue をご確認頂ければとー。

2021-06-17 23:36 UTC, shikky0331 commented
@piro0919 
すみません！細かくプルリクを分けた方がいいのかと思いまして、別プルリクでやろうとしていました。
この程度であれば分けない方がいいでしょうか？

2021-06-17 23:39 UTC, piro0919 commented
@shikky0331 

1 Issue 1 PR で良いと思いますー。
もし Issue の粒度が大きいと感じた場合、その旨を Issue のコメントに書いていただければ Issue を分割する方向で進めたいですね。 👍

2021-06-17 23:40 UTC, piro0919 commented
@shikky0331 

もし今回のケースであれば Issue のコメントに「husky の導入は別 Issue で行います」などと書いていただいて、別の Issue を切って対応する、みたいな感じですかね？

2021-06-17 23:42 UTC, shikky0331 commented
@piro0919 
承知しました！🙆‍♂️
今回のIssueは粒度が大きくないので、同じプルリクでhuskyも導入いたします！

ありがとうございます！

2021-06-17 23:44 UTC, piro0919 commented
@shikky0331 

少しでも疑問があれば遠慮せずどんどん聞いてください！
積極的なコミュニケーションだとこちらとしてはめちゃくちゃやりやすいので。

あと毎回必ずしも自分が正しいわけではないので！鵜呑みにはしないでくださいね。 😸

2021-06-17 23:46 UTC, shikky0331 commented
@piro0919 
承知しました！何かあれば積極的に質問します🙋‍♂️

はい！しっかりと自分でも考えながらやっていきます！

2021-06-19 00:06 UTC, shikky0331 commented
@piro0919 
huskyとcommitzenを追加しました！
お時間あるときに確認をお願いいたします🙇‍♂️

2021-06-19 03:55 UTC, piro0919 commented on package.json
> +      "path": "./node_modules/cz-conventional-changelog"
[must]

`path` の記述が公式と異なっていますが、理由を教えていただきたいですー。 🙇 

rel https://github.com/commitizen/cz-cli#making-your-repo-commitizen-friendly

2021-06-19 03:58 UTC, piro0919 commented on package.json
> +      "path": "./node_modules/cz-conventional-changelog"
[must]

path の記述が公式と異なっていますが、理由を教えていただきたいですー。 🙇

rel https://github.com/commitizen/cz-cli#making-your-repo-commitizen-friendly

2021-06-19 03:58 UTC, piro0919 commented on package.json
> +  },
[must]

`dependencies` と `devDependencies` の違いを教えていただきたいです。 👍 
あと、今回のプロジェクトではどう使い分けるべきか考えてみてください。 👍

2021-06-19 23:56 UTC, shikky0331 commented on package.json
> +      "path": "./node_modules/cz-conventional-changelog"
@piro0919 
https://github.com/commitizen/cz-cli#optional-install-and-run-commitizen-locally
`npx commitizen init cz-conventional-changelog --save-dev --save-exact
`npxコマンドで実行していたので、pathが`./node_modules/cz-conventional-changelog`に自動で設定されていたみたいです。

どちらのpath設定でも動作するのですが変更した方がいいでしょうか？
`commitizen`をglobalにinstallしていないので、pathを`cz-conventional-changelog`だと動作しないかと思ったのですが動きました🤔

2021-06-20 00:02 UTC, shikky0331 commented on package.json
> +  },
@piro0919 

https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file
> "dependencies": Packages required by your application in production.
> "devDependencies": Packages that are only needed for local development and testing.

`dependencies`は本番環境で使うライブラリ
`devDependencies`は開発環境とテスト環境のみで使用するライブラリ
調べたら上記のように書いてあったので、本番環境で使用しないlint系やテスト系のライブラリは`devDependencies`に配置するべきかなと思いました。

なので、今回追加したライブラリの`commitlint`, `commitzen`も`devDependencies`に変更した方が良さそうですね。。

2021-06-20 04:08 UTC, piro0919 commented on package.json
> +      "path": "./node_modules/cz-conventional-changelog"
@shikky0331 

了解ですー。
問題ないと思います。 👍

2021-06-20 04:10 UTC, piro0919 commented on package.json
> +      "path": "./node_modules/cz-conventional-changelog"
@shikky0331 

> commitizenをglobalにinstallしていないので、pathをcz-conventional-changelogだと動作しないかと思ったのですが動きました🤔

これは認識が正しくないと思います。
確か `package.json` と同じ階層以下であれば `node_modules` 内を直接参照することが可能だったと思います。

2021-06-20 04:13 UTC, piro0919 commented on package.json
> +  },
@shikky0331 

確か Create React App の場合はすべてのパッケージを `dependencies` に集約しても問題なかったと思います。
https://stackoverflow.com/questions/44868453/create-react-app-install-devdepencies-in-dependencies-section

とはいえ細かい話なので、今回はあまり気にしなくても良いとは思います。

2021-06-20 04:15 UTC, piro0919 commented
@shikky0331 

再レビューが必要でしたら、再リクエストお願いしますー。 🙇

2021-06-20 22:48 UTC, shikky0331 commented on package.json
> +      "path": "./node_modules/cz-conventional-changelog"
@piro0919 

> 確か `package.json` と同じ階層以下であれば `node_modules` 内を直接参照することが可能だったと思います。

なるほどです！だから`node_modules`を指定しなくても参照できるのですね！
説明ありがとうございます🙇‍♂️

2021-06-21 01:09 UTC, piro0919 approved these changes
LGTM 👍

2021-06-21 01:09 UTC, merged