Blogページを作成
shikky0331/shikky pull request #50
Opened 2021-08-09 23:24 UTC by shikky0331

close #27

2021-08-10 00:59 UTC, piro0919 requested changes

2021-08-10 00:59 UTC, piro0919 commented on src/containers/index.tsx
> +import Blog from 'containers/pages/Blog/index';
[must]

`index` は不要ですね。 🙅‍♂️

2021-08-10 00:59 UTC, piro0919 commented on src/containers/index.tsx
> +import Blog from 'containers/pages/Blog/index';
[imo]

各 container component のフォルダ名は lower で統一したほうが好みですね。 😃

2021-08-10 00:59 UTC, piro0919 commented on src/containers/pages/Blog/index.tsx
> +          .then((text) => setMarkdown(text));
[imo]

callback 地獄になっちゃってますね。 😈 
`useEffect` 内なので微妙ですが、async-await に書き換えるのもアリだと思います。

2021-08-10 00:59 UTC, piro0919 commented on src/containers/pages/Blog/index.tsx
> +const Blog = (): ReactElement => {
[must]

`VFC` 型と `ReactElement` 型が混在していますが、なにか意図がありますか？
統一性を意識しましょう。 👍

2021-08-10 00:59 UTC, piro0919 commented on src/containers/pages/Blog/index.tsx
> +    const markdownPath = import(`./markdowns/${date}.md`);
[imo]

対応するマークダウンファイルが見つからなかった場合の考慮もほしいですね。
あとから実装でも良いと思います。 😺

2021-08-13 04:37 UTC, shikky0331 commented on src/containers/pages/Blog/index.tsx
> +          .then((text) => setMarkdown(text));
[`bb5f57c` (#50)](https://github.com/shikky0331/shikky/pull/50/commits/bb5f57c0afc754d6040679a8c3aada612d556fca)
こちらで修正しましたmm

2021-08-13 04:37 UTC, shikky0331 commented on src/containers/pages/Blog/index.tsx
> +    const markdownPath = import(`./markdowns/${date}.md`);
[`bb5f57c` (#50)](https://github.com/shikky0331/shikky/pull/50/commits/bb5f57c0afc754d6040679a8c3aada612d556fca#diff-c813f421c50abe04e55271627bbe53afdbbfb641a6c85545e412068ac69daf15R21)
エラー処理を追加しました！

2021-08-13 04:38 UTC, shikky0331 commented on src/containers/pages/Blog/index.tsx
> +const Blog = (): ReactElement => {
https://github.com/shikky0331/shikky/pull/50/files/32ce53b1409a9535c3b1149371f97a8a99f0efec#diff-c813f421c50abe04e55271627bbe53afdbbfb641a6c85545e412068ac69daf15R24 の返り値が`ReactElement`のため、`VFC`ではなく`ReactElement`にしました！🐈

2021-08-13 04:39 UTC, shikky0331 commented on src/containers/index.tsx
> +import Blog from 'containers/pages/Blog/index';
[`c937077` (#50)](https://github.com/shikky0331/shikky/pull/50/commits/c9370772f302c01fa631ef90a71536ca4d7c3d56)
lowerで統一しました🐎

2021-08-14 08:20 UTC, piro0919 commented on src/containers/pages/Blog/index.tsx
> +const Blog = (): ReactElement => {
[must]

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d195fb003a300937e6da60bc3d7e7bff548db519/types/react/index.d.ts#L554
VFC も戻り値が ReactElement なので問題ないと思いますが、どうでしょうか。 👀

2021-08-14 08:26 UTC, piro0919 requested changes
細かい指摘が多いですが！

2021-08-14 08:26 UTC, piro0919 commented on src/containers/index.tsx
> +import Blog from 'containers/pages/blog';
[imo]

pages 以下のフォルダ階層は url のパスに合わせたほうが保守性が上がると思いますが、どうでしょうか？
`import Date from 'containers/pages/blog/date';` とかですかね？

今のままだと、仮に後から `/blog` というパスを切ろうとした場合にフォルダの構成がうまくいかなくなるかなと。

2021-08-14 08:26 UTC, piro0919 commented on src/containers/pages/blog/index.tsx
> +    fetchMarkdownData().catch(() => setMarkdown('# Not found a article.'));
[imo]

ここで catch 構文をチェーンでつなげるのはちょっと微妙な気がしますね。
`fetchMarkdownData` 関数内で `try-catch` を入れてやるほうがスコープが厳密で良いかなと思います。 😄

2021-08-15 02:08 UTC, shikky0331 commented on src/containers/pages/Blog/index.tsx
> +const Blog = (): ReactElement => {
`Type 'ReactElement<any, any>' provides no match for the signature '(props: {}, context?: any): ReactElement<any, any> | null'.ts(2322)`
上記のエラーが生じてしまいます。

2021-08-15 02:22 UTC, piro0919 commented on src/containers/pages/Blog/index.tsx
> +const Blog = (): ReactElement => {
VFC は戻り値の型ではないですよ 👀 
コンポーネント自体の型ですね。

https://github.com/shikky0331/shikky/blob/75297ba80b9e70779f3edfc87a0d5eb8ac9b00e5/src/containers/index.tsx#L9
🙆‍♂️  `const Containers: VFC = () => (`
🙅‍♂️  `const Containers = (): VFC => (`

2021-08-15 02:23 UTC, shikky0331 commented on src/containers/index.tsx
> +import Blog from 'containers/pages/blog';
[`6968c8c` (#50)](https://github.com/shikky0331/shikky/pull/50/commits/6968c8c69ad710a9880e6770ce6da9ea2722882a)
上記の修正で認識は合っているでしょうか？🐶
間違っていたらすみませんmm

2021-08-15 02:23 UTC, shikky0331 commented on src/containers/pages/blog/index.tsx
> +    fetchMarkdownData().catch(() => setMarkdown('# Not found a article.'));
確かにスコープがわかりやすいですね！修正しました！！

[`ac5932d` (#50)](https://github.com/shikky0331/shikky/pull/50/commits/ac5932dce26e1ded279d1dd1fb218f081a235ff4)

2021-08-15 02:25 UTC, shikky0331 commented on src/containers/pages/Blog/index.tsx
> +const Blog = (): ReactElement => {
ああ！！理解しました🙇‍♂️
ありがとうございます！！

2021-08-15 02:28 UTC, shikky0331 commented on src/containers/pages/Blog/index.tsx
> +const Blog = (): ReactElement => {
[`111ec3e` (#50)](https://github.com/shikky0331/shikky/pull/50/commits/111ec3eabdbb96a80fcb20af4b99c230f9b67b3f)
こちらで修正しました！🦔

2021-08-15 02:32 UTC, piro0919 requested changes
[must]

ファイルがダブっちゃってるので修正お願いしますー。 🙇

2021-08-15 12:03 UTC, shikky0331 commented
[`505bcbe` (#50)](https://github.com/shikky0331/shikky/pull/50/commits/505bcbea8c283380bca497b250f3ce0554ba43ff)
すみません、確認不足でした。こちらで削除しました🙇‍♂️

2021-08-15 12:04 UTC, piro0919 requested changes

2021-08-15 12:04 UTC, piro0919 commented on src/containers/pages/blog/date/index.tsx
> +    fetchMarkdownData().catch(() => setMarkdown('# Not found a article.'));
[must]

エラーハンドリングが戻っちゃってるので再度確認お願いしますー。 🙇

2021-08-15 23:13 UTC, shikky0331 commented on src/containers/pages/blog/date/index.tsx
> +    fetchMarkdownData().catch(() => setMarkdown('# Not found a article.'));
[`8332889` (#50)](https://github.com/shikky0331/shikky/pull/50/commits/833288909390fc5cd4a6d712994e35f09441fb9e)
何度もすみません。。🙇‍♂️
修正しました。

2021-08-16 00:59 UTC, piro0919 approved these changes
LGTM 👍

2021-08-16 00:59 UTC, merged