SEO対策をするためにreact-helmetを追加
shikky0331/shikky pull request #64
Opened 2021-08-26 10:35 UTC by shikky0331

- feat: add react-helmet for seo
- feat: add react-helmet to containers/index
- feat: add templates/Seo component

close #54

2021-08-26 15:18 UTC, piro0919 requested changes

2021-08-26 15:18 UTC, piro0919 commented on src/components/templates/Seo/index.tsx
> +type SeoArgs = {
[imo]

命名は `SeoProps` のほうが自然かなーと思います。 🏞️

2021-08-26 15:18 UTC, piro0919 commented on src/components/templates/Seo/index.tsx
> +import { FC, VFC } from 'react';
[must]

`VFC` が使われてないですね。 🙅‍♂️

2021-08-26 15:18 UTC, piro0919 commented on src/components/templates/Seo/index.tsx
> +const Seo: FC<SeoArgs> = ({
[imo]

他のコンポーネントでは `VFC` が使われてますが、使い分けの意図を教えて教えて頂きたいですー。 🙇

2021-08-26 15:18 UTC, piro0919 commented on src/containers/pages/blog/date/index.tsx
> +  const articleInfo = articles.find((article) => article.url.includes(date));
[imo]

`useMemo` を使ってもいいかとー。 📝

2021-08-26 15:18 UTC, piro0919 commented on src/containers/index.tsx
> +    </Helmet>
[imo]

`Containers` コンポーネントで共通のタグを埋めるよりは、各 container コンポーネントから `Seo` コンポーネントを逐一呼び出して、共通のタグは `Seo` コンポーネントに埋め込むほうが好きですね。

この書き方だと `Containers` コンポーネントと `Seo` コンポーネントの 2 箇所でタグを見ることになってしまうので、ちょっと保守性がイマイチかなと。

2021-08-26 15:18 UTC, piro0919 commented on src/containers/pages/blog/date/index.tsx
> +        url={`shikky${articleInfo?.url}`}
[must]

確かフルパス必須だったような。

2021-08-28 00:24 UTC, shikky0331 commented on src/components/templates/Seo/index.tsx
> +const Seo: FC<SeoArgs> = ({
[`f04a80f` (#64)](https://github.com/shikky0331/shikky/pull/64/commits/f04a80f22487398b4d0e5490e6f6d05dccf8c5f9)
こちらミスです🙇‍♂️ VFCに変更しました！

2021-08-28 00:24 UTC, shikky0331 commented on src/components/templates/Seo/index.tsx
> +import { FC, VFC } from 'react';
https://github.com/shikky0331/shikky/pull/64#discussion_r697775143
こちらでFCからVFCに変更しました。🐪

2021-08-28 00:25 UTC, shikky0331 commented on src/components/templates/Seo/index.tsx
> +type SeoArgs = {
[`08531f1` (#64)](https://github.com/shikky0331/shikky/pull/64/commits/08531f1990f54dfa5e19f99513aa6314956ae963)
変更しました！🐕

2021-08-28 00:26 UTC, shikky0331 commented on src/containers/pages/blog/date/index.tsx
> +        url={`shikky${articleInfo?.url}`}
[`05053eb` (#64)](https://github.com/shikky0331/shikky/pull/64/commits/05053eb4edc01556ccaa4e072d23853d4c2c34d5)
調べたらフルパス必須だったので修正しました🙇‍♂️

2021-08-28 00:27 UTC, shikky0331 commented on src/containers/pages/blog/date/index.tsx
> +  const articleInfo = articles.find((article) => article.url.includes(date));
今まであまり使ったことなかったのです...
修正しました！🦓
[`e82a151` (#64)](https://github.com/shikky0331/shikky/pull/64/commits/e82a1511a538881154e9466498bc8cba2f8f437d)

2021-08-28 00:29 UTC, shikky0331 commented on src/containers/index.tsx
> +    </Helmet>
共通の処理は`Container`にまとめた方がわかりやすいかと思ってしましたが、下記の視点は抜けてました... ありがとうございます！

> 2 箇所でタグを見ることになってしまうので

こちらで修正しました🐇
[`51da89d` (#64)](https://github.com/shikky0331/shikky/pull/64/commits/51da89d547f9a5b1e68b7c1f50afbf873c95cba3)

2021-08-28 00:30 UTC, shikky0331 commented
レビューありがとうございます！勉強になります📝

2021-08-29 01:41 UTC, piro0919 requested changes
細かめですが。

2021-08-29 01:41 UTC, piro0919 commented on src/containers/index.tsx
> +  <>
[must]

不要ですね。

2021-08-29 01:41 UTC, piro0919 commented on src/containers/pages/blog/date/index.tsx
> +        url={`https://shikky0331.github.io/shikky${articleInfo?.url}`}
[imo]

この書き方だと画面が増えるごとに絶対パスを書くことになってしまうので、props は `https://shikky0331.github.io/shikky` 以下を渡すほうが保守性が高いかなーと思います。 🐦

2021-08-29 01:41 UTC, piro0919 commented on src/components/templates/Seo/index.tsx
> +  ogImage?: string
[imo]

ここって本当に全部 optional が好ましいですかね？
例えば ogType とかは optional である理由がなさそうに見えます。

もう少し厳密に設定したほうが良いかもです。 👍

2021-08-29 23:48 UTC, shikky0331 commented on src/components/templates/Seo/index.tsx
> +  ogImage?: string
ogTypeは直接文字列で値を渡しているのでoptionalの必要がないですね！！
気づいてなかったです。。ありがとうございます！！🐹

2021-08-29 23:56 UTC, shikky0331 commented on src/containers/index.tsx
> +  <>
[`51ffd61` (#64)](https://github.com/shikky0331/shikky/pull/64/commits/51ffd61f8d6a0b46c7bc81c28f7aed38d1943093)
削除しました！🐩

2021-08-29 23:57 UTC, shikky0331 commented on src/containers/pages/blog/date/index.tsx
> +        url={`https://shikky0331.github.io/shikky${articleInfo?.url}`}
なるほどです！こういった考慮は大切ですね！！📝

[`2d17fea` (#64)](https://github.com/shikky0331/shikky/pull/64/commits/2d17fea3b85e2e412cb1b3dccda3cca3b518224c)
こちらで変更しました🦝

2021-08-29 23:58 UTC, shikky0331 commented on src/components/templates/Seo/index.tsx
> +  ogImage?: string
こちらで修正しました🐕
[`b23c706` (#64)](https://github.com/shikky0331/shikky/pull/64/commits/b23c7065d7ea175d08fcd1651f05a6952d271267)

2021-08-30 10:25 UTC, piro0919 approved these changes
LGTM 👍

2021-08-30 10:25 UTC, merged