create-react-appで作成された使用しないコードを削除する
shikky0331/shikky pull request #8
Opened 2021-06-20 02:31 UTC by shikky0331

2021-06-20 04:17 UTC, piro0919 requested changes
大体良い感じです。 👍

2021-06-20 04:17 UTC, piro0919 commented on public/index.html
> -    <meta name="viewport" content="width=device-width, initial-scale=1" />
[imo]

ここは残しておいても良いかなと思います。
内容についても調べてみてください。 👍

2021-06-20 04:17 UTC, piro0919 commented on public/index.html
> -    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
[imo]

ここも残しておいても良いかなと思います。
内容についても調べてみてください。 👍

2021-06-20 04:17 UTC, piro0919 commented on public/manifest.json
> -}
[imo]

このファイルは残しておきましょうか。

2021-06-20 04:17 UTC, piro0919 commented on public/robots.txt
> -Disallow:
[imo]

こちらも残しておきましょうか。

2021-06-20 23:26 UTC, shikky0331 commented on public/index.html
> -    <meta name="viewport" content="width=device-width, initial-scale=1" />
@piro0919 
`link rel="icon" href="%PUBLIC_URL%/favicon.ico" />`
使用するfaviconを指定。

`<meta name="viewport" content="width=device-width, initial-scale=1" />`
https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag#viewport_basics
画面表示の設定。
`device-width`は端末ごとに幅が動的に変更される。
`initial-scale`は画面を表示したときのzoom率。

2021-06-20 23:28 UTC, shikky0331 commented on public/index.html
> -    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
@piro0919 

https://developer.mozilla.org/en-US/docs/Web/Manifest
PWAに関する設定を行うfileを指定する

2021-06-20 23:29 UTC, shikky0331 commented
@piro0919 
必要なファイルを復元して、内容を調べました！
お時間あるときに確認をお願いします🙇‍♂️

2021-06-21 01:08 UTC, piro0919 approved these changes
LGTM 👍

2021-06-21 01:08 UTC, merged